### PR TITLE
Add support for loading multiple input files of the same type

### PR DESCRIPTION
**Pull request by bartvanandel**
This PR adds support for loading more than 1 file (of the same type) for processing into a single heat map. Example use case: see which roads I've been taken most during multiple rides.
 
* Add support for repeated arguments
* Add support for glob wildcards

See also my other PR, which can be used to boost hardly used pixels so you can at least see them.

### CODE REVIEW

**Comment by sethoscope** [comment]
This is all good, but looking with fresh eyes at how I organized file reading makes me want to tear it out and try again. When it was one file of one type, it made little difference how it was specified, but it grew awkwardly. If the input file were a positional argument, we could support multiple input files with unrelated names without requiring awkward globs to join them in one argument, and where globbing is useful we could let the shell handle it. Also we could guess the type from the filename, and when that's good enough, even allow mixing types (though I'm not sure anyone would ever need that).

The only catch is that it's not backward compatible, but I'm not sure there are any ongoing uses out there. My guess is that most people grab this script once, use it for some project, never upgrade, and won't care if I change the command line, and that substantial improvements make it worth a little breakage. But that guess isn't really based on anything.

I took a stab at it and stuck it [in a branch](/sethoscope/heatmap/tree/fileargs). It's a bigger reorg, but it feels better to have reader classes, and the format detection is a nice plus for the user.  What do you think?

**Comment by hugovk** [comment]
If you bump the version number and make it clear somewhere how it's backward compatible, and how to update, I'm sure that'll be fine!

**Comment by sethoscope** [comment]
I realized I can make it backwardly compatible for a year or two at a cost of code aesthetics, so that's what I'll do.  Thank you, Bart, for the kick in the pants and the helpful reference implementation. I think your patch was more reasonable, but I decided to do something more ambitious.  :)

**Comment by bartvanandel** [comment]
I've tried the new 'fileargs' branch and although I think this is the way forward (bravo for that), it isn't currently working for me. I'm trying to run the script using a wildcard argument, which fails by default (at least on Windows 10, unix shells may expand glob arguments automatically). This is why I had added 'glob' support manually.

To illustrate, this is what I'm getting with the current tip of the 'fileargs' branch:

``` .cmd
D:\src\external\github\heatman\tmp> ..\heatmap.py -o heat.png --height 1024 input\*.gpx
Traceback (most recent call last):
  File "D:\src\external\github\heatmap\heatmap.py", line 1255, in <module>
    main()
  File "D:\src\external\github\heatmap\heatmap.py", line 1234, in main
    config.fill_missing()
  File "D:\src\external\github\heatmap\heatmap.py", line 1183, in fill_missing
    self.shapes = list(self.shapes)
  File "D:\src\external\github\heatmap\heatmap.py", line 804, in read_file
    for trkseg in track.segments():
  File "D:\src\external\github\heatmap\heatmap.py", line 104, in _parse
    for event, elem in ET.iterparse(filename, ('start', 'end')):
  File "D:\apps\Python36\lib\xml\etree\ElementTree.py", line 1242, in iterparse
    source = open(source, "rb")
OSError: [Errno 22] Invalid argument: 'input\\*.gpx'
```

Maybe I'll take a look at it later today. Right now, the sun is shining, so I'm going to take advantage of a natural heat map ;)

**Comment by sethoscope** [comment]
Ah. I didn't realize the Windows command shell doesn't handle wildcard expansion. I had a look around and found discussing of this problem going back 15 years. The best solution I saw, which is not perfect, appears to be: do globbing on Windows, don't do it otherwise. So I've added that. I tested it as best I could without a Windows machine. Let me know how it goes.

**Comment by bartvanandel** [comment]
Works like a charm, great work! 👍
Time to merge the new branch to master then I suppose! This pretty much supersedes and exceeds everything in this PR, so I'll close it.

**Pull request closed without merging**
